server:
  port: 8283

logging:
  level:
    com.tematani: DEBUG

storage:
  tmp-location: /Users/riza/Documents/Kuliah/Tugas-Akhir/teman-tani/storage/tmp
  location: /Users/riza/Documents/Kuliah/Tugas-Akhir/teman-tani/storage

spring:
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:init-schema.sql, classpath:init-data.sql
      platform: postgres
  jpa:
    database: postgresql
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        default-schema: project

  datasource:
    url: jdbc:postgresql://localhost:5432/temantani?currentSchema=project&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
