/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.temantani.kafka.investment.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CloseFundraisingInvestmentResponseAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4517425531215038879L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CloseFundraisingInvestmentResponseAvroModel\",\"namespace\":\"com.temantani.kafka.investment.avro.model\",\"fields\":[{\"name\":\"investmentId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"investorId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"amount\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":10,\"scale\":2}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<CloseFundraisingInvestmentResponseAvroModel> ENCODER =
      new BinaryMessageEncoder<CloseFundraisingInvestmentResponseAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CloseFundraisingInvestmentResponseAvroModel> DECODER =
      new BinaryMessageDecoder<CloseFundraisingInvestmentResponseAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CloseFundraisingInvestmentResponseAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CloseFundraisingInvestmentResponseAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CloseFundraisingInvestmentResponseAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CloseFundraisingInvestmentResponseAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CloseFundraisingInvestmentResponseAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CloseFundraisingInvestmentResponseAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CloseFundraisingInvestmentResponseAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CloseFundraisingInvestmentResponseAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String investmentId;
  private java.lang.String investorId;
  private java.math.BigDecimal amount;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CloseFundraisingInvestmentResponseAvroModel() {}

  /**
   * All-args constructor.
   * @param investmentId The new value for investmentId
   * @param investorId The new value for investorId
   * @param amount The new value for amount
   */
  public CloseFundraisingInvestmentResponseAvroModel(java.lang.String investmentId, java.lang.String investorId, java.math.BigDecimal amount) {
    this.investmentId = investmentId;
    this.investorId = investorId;
    this.amount = amount;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return investmentId;
    case 1: return investorId;
    case 2: return amount;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      new org.apache.avro.Conversions.DecimalConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: investmentId = value$ != null ? value$.toString() : null; break;
    case 1: investorId = value$ != null ? value$.toString() : null; break;
    case 2: amount = (java.math.BigDecimal)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'investmentId' field.
   * @return The value of the 'investmentId' field.
   */
  public java.lang.String getInvestmentId() {
    return investmentId;
  }


  /**
   * Sets the value of the 'investmentId' field.
   * @param value the value to set.
   */
  public void setInvestmentId(java.lang.String value) {
    this.investmentId = value;
  }

  /**
   * Gets the value of the 'investorId' field.
   * @return The value of the 'investorId' field.
   */
  public java.lang.String getInvestorId() {
    return investorId;
  }


  /**
   * Sets the value of the 'investorId' field.
   * @param value the value to set.
   */
  public void setInvestorId(java.lang.String value) {
    this.investorId = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public java.math.BigDecimal getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(java.math.BigDecimal value) {
    this.amount = value;
  }

  /**
   * Creates a new CloseFundraisingInvestmentResponseAvroModel RecordBuilder.
   * @return A new CloseFundraisingInvestmentResponseAvroModel RecordBuilder
   */
  public static com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel.Builder newBuilder() {
    return new com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel.Builder();
  }

  /**
   * Creates a new CloseFundraisingInvestmentResponseAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CloseFundraisingInvestmentResponseAvroModel RecordBuilder
   */
  public static com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel.Builder newBuilder(com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel.Builder other) {
    if (other == null) {
      return new com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel.Builder();
    } else {
      return new com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new CloseFundraisingInvestmentResponseAvroModel RecordBuilder by copying an existing CloseFundraisingInvestmentResponseAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new CloseFundraisingInvestmentResponseAvroModel RecordBuilder
   */
  public static com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel.Builder newBuilder(com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel other) {
    if (other == null) {
      return new com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel.Builder();
    } else {
      return new com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for CloseFundraisingInvestmentResponseAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CloseFundraisingInvestmentResponseAvroModel>
    implements org.apache.avro.data.RecordBuilder<CloseFundraisingInvestmentResponseAvroModel> {

    private java.lang.String investmentId;
    private java.lang.String investorId;
    private java.math.BigDecimal amount;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.investmentId)) {
        this.investmentId = data().deepCopy(fields()[0].schema(), other.investmentId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.investorId)) {
        this.investorId = data().deepCopy(fields()[1].schema(), other.investorId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.amount)) {
        this.amount = data().deepCopy(fields()[2].schema(), other.amount);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing CloseFundraisingInvestmentResponseAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.investmentId)) {
        this.investmentId = data().deepCopy(fields()[0].schema(), other.investmentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.investorId)) {
        this.investorId = data().deepCopy(fields()[1].schema(), other.investorId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.amount)) {
        this.amount = data().deepCopy(fields()[2].schema(), other.amount);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'investmentId' field.
      * @return The value.
      */
    public java.lang.String getInvestmentId() {
      return investmentId;
    }


    /**
      * Sets the value of the 'investmentId' field.
      * @param value The value of 'investmentId'.
      * @return This builder.
      */
    public com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel.Builder setInvestmentId(java.lang.String value) {
      validate(fields()[0], value);
      this.investmentId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'investmentId' field has been set.
      * @return True if the 'investmentId' field has been set, false otherwise.
      */
    public boolean hasInvestmentId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'investmentId' field.
      * @return This builder.
      */
    public com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel.Builder clearInvestmentId() {
      investmentId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'investorId' field.
      * @return The value.
      */
    public java.lang.String getInvestorId() {
      return investorId;
    }


    /**
      * Sets the value of the 'investorId' field.
      * @param value The value of 'investorId'.
      * @return This builder.
      */
    public com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel.Builder setInvestorId(java.lang.String value) {
      validate(fields()[1], value);
      this.investorId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'investorId' field has been set.
      * @return True if the 'investorId' field has been set, false otherwise.
      */
    public boolean hasInvestorId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'investorId' field.
      * @return This builder.
      */
    public com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel.Builder clearInvestorId() {
      investorId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public java.math.BigDecimal getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel.Builder setAmount(java.math.BigDecimal value) {
      validate(fields()[2], value);
      this.amount = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel.Builder clearAmount() {
      amount = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CloseFundraisingInvestmentResponseAvroModel build() {
      try {
        CloseFundraisingInvestmentResponseAvroModel record = new CloseFundraisingInvestmentResponseAvroModel();
        record.investmentId = fieldSetFlags()[0] ? this.investmentId : (java.lang.String) defaultValue(fields()[0]);
        record.investorId = fieldSetFlags()[1] ? this.investorId : (java.lang.String) defaultValue(fields()[1]);
        record.amount = fieldSetFlags()[2] ? this.amount : (java.math.BigDecimal) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CloseFundraisingInvestmentResponseAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<CloseFundraisingInvestmentResponseAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CloseFundraisingInvestmentResponseAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<CloseFundraisingInvestmentResponseAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










