/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.temantani.kafka.investment.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CloseFundraisingResponseAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7453976314956280638L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CloseFundraisingResponseAvroModel\",\"namespace\":\"com.temantani.kafka.investment.avro.model\",\"fields\":[{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"CloseFundraisingStatusResponseAvroModel\",\"symbols\":[\"CLOSING\",\"CLOSED\"]}},{\"name\":\"projectId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"investments\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"CloseFundraisingInvestmentResponseAvroModel\",\"fields\":[{\"name\":\"investmentId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"investorId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"amount\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":10,\"scale\":2}}]},\"default\":[]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<CloseFundraisingResponseAvroModel> ENCODER =
      new BinaryMessageEncoder<CloseFundraisingResponseAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CloseFundraisingResponseAvroModel> DECODER =
      new BinaryMessageDecoder<CloseFundraisingResponseAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CloseFundraisingResponseAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CloseFundraisingResponseAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CloseFundraisingResponseAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CloseFundraisingResponseAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CloseFundraisingResponseAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CloseFundraisingResponseAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CloseFundraisingResponseAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CloseFundraisingResponseAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private com.temantani.kafka.investment.avro.model.CloseFundraisingStatusResponseAvroModel status;
  private java.lang.String projectId;
  private java.util.List<com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel> investments;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CloseFundraisingResponseAvroModel() {}

  /**
   * All-args constructor.
   * @param status The new value for status
   * @param projectId The new value for projectId
   * @param investments The new value for investments
   */
  public CloseFundraisingResponseAvroModel(com.temantani.kafka.investment.avro.model.CloseFundraisingStatusResponseAvroModel status, java.lang.String projectId, java.util.List<com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel> investments) {
    this.status = status;
    this.projectId = projectId;
    this.investments = investments;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return status;
    case 1: return projectId;
    case 2: return investments;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: status = (com.temantani.kafka.investment.avro.model.CloseFundraisingStatusResponseAvroModel)value$; break;
    case 1: projectId = value$ != null ? value$.toString() : null; break;
    case 2: investments = (java.util.List<com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public com.temantani.kafka.investment.avro.model.CloseFundraisingStatusResponseAvroModel getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(com.temantani.kafka.investment.avro.model.CloseFundraisingStatusResponseAvroModel value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'projectId' field.
   * @return The value of the 'projectId' field.
   */
  public java.lang.String getProjectId() {
    return projectId;
  }


  /**
   * Sets the value of the 'projectId' field.
   * @param value the value to set.
   */
  public void setProjectId(java.lang.String value) {
    this.projectId = value;
  }

  /**
   * Gets the value of the 'investments' field.
   * @return The value of the 'investments' field.
   */
  public java.util.List<com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel> getInvestments() {
    return investments;
  }


  /**
   * Sets the value of the 'investments' field.
   * @param value the value to set.
   */
  public void setInvestments(java.util.List<com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel> value) {
    this.investments = value;
  }

  /**
   * Creates a new CloseFundraisingResponseAvroModel RecordBuilder.
   * @return A new CloseFundraisingResponseAvroModel RecordBuilder
   */
  public static com.temantani.kafka.investment.avro.model.CloseFundraisingResponseAvroModel.Builder newBuilder() {
    return new com.temantani.kafka.investment.avro.model.CloseFundraisingResponseAvroModel.Builder();
  }

  /**
   * Creates a new CloseFundraisingResponseAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CloseFundraisingResponseAvroModel RecordBuilder
   */
  public static com.temantani.kafka.investment.avro.model.CloseFundraisingResponseAvroModel.Builder newBuilder(com.temantani.kafka.investment.avro.model.CloseFundraisingResponseAvroModel.Builder other) {
    if (other == null) {
      return new com.temantani.kafka.investment.avro.model.CloseFundraisingResponseAvroModel.Builder();
    } else {
      return new com.temantani.kafka.investment.avro.model.CloseFundraisingResponseAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new CloseFundraisingResponseAvroModel RecordBuilder by copying an existing CloseFundraisingResponseAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new CloseFundraisingResponseAvroModel RecordBuilder
   */
  public static com.temantani.kafka.investment.avro.model.CloseFundraisingResponseAvroModel.Builder newBuilder(com.temantani.kafka.investment.avro.model.CloseFundraisingResponseAvroModel other) {
    if (other == null) {
      return new com.temantani.kafka.investment.avro.model.CloseFundraisingResponseAvroModel.Builder();
    } else {
      return new com.temantani.kafka.investment.avro.model.CloseFundraisingResponseAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for CloseFundraisingResponseAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CloseFundraisingResponseAvroModel>
    implements org.apache.avro.data.RecordBuilder<CloseFundraisingResponseAvroModel> {

    private com.temantani.kafka.investment.avro.model.CloseFundraisingStatusResponseAvroModel status;
    private java.lang.String projectId;
    private java.util.List<com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel> investments;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.temantani.kafka.investment.avro.model.CloseFundraisingResponseAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.status)) {
        this.status = data().deepCopy(fields()[0].schema(), other.status);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.projectId)) {
        this.projectId = data().deepCopy(fields()[1].schema(), other.projectId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.investments)) {
        this.investments = data().deepCopy(fields()[2].schema(), other.investments);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing CloseFundraisingResponseAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.temantani.kafka.investment.avro.model.CloseFundraisingResponseAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.status)) {
        this.status = data().deepCopy(fields()[0].schema(), other.status);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.projectId)) {
        this.projectId = data().deepCopy(fields()[1].schema(), other.projectId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.investments)) {
        this.investments = data().deepCopy(fields()[2].schema(), other.investments);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public com.temantani.kafka.investment.avro.model.CloseFundraisingStatusResponseAvroModel getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.temantani.kafka.investment.avro.model.CloseFundraisingResponseAvroModel.Builder setStatus(com.temantani.kafka.investment.avro.model.CloseFundraisingStatusResponseAvroModel value) {
      validate(fields()[0], value);
      this.status = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.temantani.kafka.investment.avro.model.CloseFundraisingResponseAvroModel.Builder clearStatus() {
      status = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'projectId' field.
      * @return The value.
      */
    public java.lang.String getProjectId() {
      return projectId;
    }


    /**
      * Sets the value of the 'projectId' field.
      * @param value The value of 'projectId'.
      * @return This builder.
      */
    public com.temantani.kafka.investment.avro.model.CloseFundraisingResponseAvroModel.Builder setProjectId(java.lang.String value) {
      validate(fields()[1], value);
      this.projectId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'projectId' field has been set.
      * @return True if the 'projectId' field has been set, false otherwise.
      */
    public boolean hasProjectId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'projectId' field.
      * @return This builder.
      */
    public com.temantani.kafka.investment.avro.model.CloseFundraisingResponseAvroModel.Builder clearProjectId() {
      projectId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'investments' field.
      * @return The value.
      */
    public java.util.List<com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel> getInvestments() {
      return investments;
    }


    /**
      * Sets the value of the 'investments' field.
      * @param value The value of 'investments'.
      * @return This builder.
      */
    public com.temantani.kafka.investment.avro.model.CloseFundraisingResponseAvroModel.Builder setInvestments(java.util.List<com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel> value) {
      validate(fields()[2], value);
      this.investments = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'investments' field has been set.
      * @return True if the 'investments' field has been set, false otherwise.
      */
    public boolean hasInvestments() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'investments' field.
      * @return This builder.
      */
    public com.temantani.kafka.investment.avro.model.CloseFundraisingResponseAvroModel.Builder clearInvestments() {
      investments = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CloseFundraisingResponseAvroModel build() {
      try {
        CloseFundraisingResponseAvroModel record = new CloseFundraisingResponseAvroModel();
        record.status = fieldSetFlags()[0] ? this.status : (com.temantani.kafka.investment.avro.model.CloseFundraisingStatusResponseAvroModel) defaultValue(fields()[0]);
        record.projectId = fieldSetFlags()[1] ? this.projectId : (java.lang.String) defaultValue(fields()[1]);
        record.investments = fieldSetFlags()[2] ? this.investments : (java.util.List<com.temantani.kafka.investment.avro.model.CloseFundraisingInvestmentResponseAvroModel>) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CloseFundraisingResponseAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<CloseFundraisingResponseAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CloseFundraisingResponseAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<CloseFundraisingResponseAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










