/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.temantani.kafka.investment.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum CloseFundraisingStatusResponseAvroModel implements org.apache.avro.generic.GenericEnumSymbol<CloseFundraisingStatusResponseAvroModel> {
  CLOSING, CLOSED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CloseFundraisingStatusResponseAvroModel\",\"namespace\":\"com.temantani.kafka.investment.avro.model\",\"symbols\":[\"CLOSING\",\"CLOSED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
